// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: api/learning/learning.proto

package learning

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClassRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TeacherID string `protobuf:"bytes,1,opt,name=teacherID,proto3" json:"teacherID,omitempty"`
	SubjectID string `protobuf:"bytes,2,opt,name=subjectID,proto3" json:"subjectID,omitempty"`
}

func (x *CreateClassRoomRequest) Reset() {
	*x = CreateClassRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_learning_learning_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateClassRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClassRoomRequest) ProtoMessage() {}

func (x *CreateClassRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_learning_learning_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClassRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateClassRoomRequest) Descriptor() ([]byte, []int) {
	return file_api_learning_learning_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClassRoomRequest) GetTeacherID() string {
	if x != nil {
		return x.TeacherID
	}
	return ""
}

func (x *CreateClassRoomRequest) GetSubjectID() string {
	if x != nil {
		return x.SubjectID
	}
	return ""
}

type ClassRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassRoomID string `protobuf:"bytes,1,opt,name=classRoomID,proto3" json:"classRoomID,omitempty"`
}

func (x *ClassRoom) Reset() {
	*x = ClassRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_learning_learning_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassRoom) ProtoMessage() {}

func (x *ClassRoom) ProtoReflect() protoreflect.Message {
	mi := &file_api_learning_learning_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassRoom.ProtoReflect.Descriptor instead.
func (*ClassRoom) Descriptor() ([]byte, []int) {
	return file_api_learning_learning_proto_rawDescGZIP(), []int{1}
}

func (x *ClassRoom) GetClassRoomID() string {
	if x != nil {
		return x.ClassRoomID
	}
	return ""
}

var File_api_learning_learning_proto protoreflect.FileDescriptor

var file_api_learning_learning_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2f, 0x6c,
	0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x54, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x65, 0x61, 0x63, 0x68, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x44, 0x22, 0x2d, 0x0a,
	0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6c,
	0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x32, 0x5d, 0x0a, 0x0f,
	0x4c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4a, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x6f, 0x6f, 0x6d, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e,
	0x2f, 0x6c, 0x65, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_learning_learning_proto_rawDescOnce sync.Once
	file_api_learning_learning_proto_rawDescData = file_api_learning_learning_proto_rawDesc
)

func file_api_learning_learning_proto_rawDescGZIP() []byte {
	file_api_learning_learning_proto_rawDescOnce.Do(func() {
		file_api_learning_learning_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_learning_learning_proto_rawDescData)
	})
	return file_api_learning_learning_proto_rawDescData
}

var file_api_learning_learning_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_learning_learning_proto_goTypes = []interface{}{
	(*CreateClassRoomRequest)(nil), // 0: settings.CreateClassRoomRequest
	(*ClassRoom)(nil),              // 1: settings.ClassRoom
}
var file_api_learning_learning_proto_depIdxs = []int32{
	0, // 0: settings.LearningService.CreateClassRoom:input_type -> settings.CreateClassRoomRequest
	1, // 1: settings.LearningService.CreateClassRoom:output_type -> settings.ClassRoom
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_learning_learning_proto_init() }
func file_api_learning_learning_proto_init() {
	if File_api_learning_learning_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_learning_learning_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateClassRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_learning_learning_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_learning_learning_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_learning_learning_proto_goTypes,
		DependencyIndexes: file_api_learning_learning_proto_depIdxs,
		MessageInfos:      file_api_learning_learning_proto_msgTypes,
	}.Build()
	File_api_learning_learning_proto = out.File
	file_api_learning_learning_proto_rawDesc = nil
	file_api_learning_learning_proto_goTypes = nil
	file_api_learning_learning_proto_depIdxs = nil
}
